require('conf.treesitter')
require('conf.lsp')
require('conf.comp')
require("luasnip.loaders.from_vscode").load()
require('feline-config')
require('nightfox-config')
require('autosave-config')
require('gitsigns-config')
--require('mapping').setup()
require('colorizer').setup()

